version: '3'

services: 
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: phpapiapplication
        restart: unless-stopped
        working_dir: /var/www
        volumes: 
            - C:/Users/user/Documents/backendphpapi:/var/www
        networks:
            - backendphpapi

    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - C:/Users/user/Documents/backendphpapi:/var/www
            - C:/Users/user/Documents/backendphpapi/docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - backendphpapi

networks:
    backendphpapi:
        driver: bridge